<?php

namespace app\components;

use yii\base\Widget;

class HelloWidget extends Widget
{
    public $name;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->name === null) {
            $this->name = 'Guest';
        }
        ob_start();
    }

    public function run()
    {
        $content = ob_get_clean();
        return $this->render('hello', [
            'name' => $this->name,
            'content' => $content
        ]);
        return "Hi {$this->name} {$content}";
    }
}